name: disaster_prep_app
description: Disaster Preparedness and Response Education System
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.1.5
  firebase_core: ^2.20.0
  firebase_auth: ^4.8.0
  cloud_firestore: ^5.7.0
  firebase_messaging: ^14.7.0
  flutter_local_notifications: ^15.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/Disaster.jpg
    - assets/icons/Dicon.png
